apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "nexus-oidc-proxy.fullname" . }}
  labels:
    {{- include "nexus-oidc-proxy.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "nexus-oidc-proxy.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "nexus-oidc-proxy.selectorLabels" . | nindent 8 }}
        {{- if not .Values.credentials.existingSecret.name }}
        nexus-oidc-proxy/secret-hash: '{{ include "nexus-oidc-proxy.secretContents" . | adler32sum }}'
        {{- end }}
        {{- if not .Values.config.existingConfigMap.name }}
        nexus-oidc-proxy/configmap-hash: '{{ include "nexus-oidc-proxy.configMapContents" . | adler32sum }}'
        {{- end }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "nexus-oidc-proxy.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          args:
          - --config=/etc/nexus-oidc-proxy/nexus-oidc-proxy.cfg
          - --log-level={{ .Values.logLevel }}
          env:
          - name: NEXUS_OIDC_PROXY_NEXUS_USERNAME
            valueFrom:
              secretKeyRef:
                name: {{ include "nexus-oidc-proxy.secretName" . }}
                key: {{ .Values.credentials.existingSecret.usernameKey }}
          - name: NEXUS_OIDC_PROXY_NEXUS_PASSWORD
            valueFrom:
              secretKeyRef:
                name: {{ include "nexus-oidc-proxy.secretName" . }}
                key: {{ .Values.credentials.existingSecret.passwordKey }}
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
          - name: config
            mountPath: /etc/nexus-oidc-proxy/nexus-oidc-proxy.cfg
            subPath: {{ .Values.config.existingConfigMap.key }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      volumes:
      - name: config
        configMap:
          name: {{ include "nexus-oidc-proxy.configMapName" . }}

